치지직:
  루나핀:
    식별자: affa78deac0b23d2046b8ed4856c1e62
    마크닉네임: lunapin
아프리카:
  루나핀:
    식별자: lupin0
    마크닉네임: lunapin

랜덤 보상: false
후원 보상:
  0:
    - say 가격을 0원으로 쓰면 설정 안된 가격을 의미합니다.
    - say 예를 들어 1000원, 3000원 이외 후원들은 모두 이 명령어가 실행됩니다.
    - say 물론 0원을 설정해놓지 않으면 정해놓은 가격 이외 후원은 무시됩니다.
    - say 랜덤 보상을 true로 변경 시 정해진 후원내 - 줄중 한개를 실행합니다.
    - say 랜덤 보상에서도 여러개를 같이 실행하실려면; say 옆에있는 세미콜론을 이용하여 어러개 작성이 가능합니다.
  1000:
    - say %tag% 는 후원받은 스트리머 명을 받아옵니다.
    - say %name% 은 후원자 입니다.
    - say %amount% 은 후원금액 입니다.
    - say %message% 는 후원시 작성한 내용이 포합됩니다.
  3000:
    - say bye
    - time set 14000

디버그: false
